name: pelem
description: Pelem is movie and tv catalog app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  get_it: ^7.3.0
  go_router: ^7.0.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.0
  pelem_core:
    path: modules/pelem_core
  pelem_movie:
    path: modules/pelem_movie
  pelem_profile:
    path: modules/pelem_profile
  pelem_tv:
    path: modules/pelem_tv

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - certificates/
